// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57Ck-ytI__mlpnlnBHRIO9QB7v8zFnIs',
    appId: '1:682859296367:web:d76277e23acd66c69abf9a',
    messagingSenderId: '682859296367',
    projectId: 'quiz01-e0801',
    authDomain: 'quiz01-e0801.firebaseapp.com',
    storageBucket: 'quiz01-e0801.appspot.com',
    measurementId: 'G-2415ZECJ4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvnQHLSYyQdhlWbGnjdD0aWpW_BNHIP2I',
    appId: '1:682859296367:android:c2f7d5262df8da339abf9a',
    messagingSenderId: '682859296367',
    projectId: 'quiz01-e0801',
    storageBucket: 'quiz01-e0801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0rHXcz8tYmO5VLMNECDX98DTMoGnW9s',
    appId: '1:682859296367:ios:25b59e0b1499db419abf9a',
    messagingSenderId: '682859296367',
    projectId: 'quiz01-e0801',
    storageBucket: 'quiz01-e0801.appspot.com',
    iosBundleId: 'com.example.quiz01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa0rHXcz8tYmO5VLMNECDX98DTMoGnW9s',
    appId: '1:682859296367:ios:25b59e0b1499db419abf9a',
    messagingSenderId: '682859296367',
    projectId: 'quiz01-e0801',
    storageBucket: 'quiz01-e0801.appspot.com',
    iosBundleId: 'com.example.quiz01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD57Ck-ytI__mlpnlnBHRIO9QB7v8zFnIs',
    appId: '1:682859296367:web:2ae05b3931ba832f9abf9a',
    messagingSenderId: '682859296367',
    projectId: 'quiz01-e0801',
    authDomain: 'quiz01-e0801.firebaseapp.com',
    storageBucket: 'quiz01-e0801.appspot.com',
    measurementId: 'G-WSJE747D1R',
  );
}
